name:                haskell-game
version:             0.1.0.0
github:              "bergsans/haskell-game"
license:             BSD3
author:              "Claes-Magnus Berg"
maintainer:          "claes-magnus@herebeseaswines.net"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

description:         Learning project. See README on GitHub at <https://github.com/bergsans/haskell-game#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  haskell-game-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-game

tests:
  haskell-game-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-game
